title: Bartłomiej Kiczek
logo: "/images/BK.jpg?raw=ture"
description: >
    <br>
    Theoretical Physicist and Data Scientist with several years of experience in numerical analysis, qunatitative analytics and machine learning. Master's (almost a PhD) in physics, author of numerous papers published in renowned scientific journals.
    <br><br>
    <a href="https://www.linkedin.com/in/bartłomiej-kiczek-870a77250/">See my LinkedIn profile</a>
    
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown